### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @royqh1979.

### CODE REVIEW

**Comment by royqh1979** [comment]
Thanks!

But I don't use MSVC to compile RedPanda-C++,and may not "respond to any feedback in your PR"(as in README.md of winget-pkg) and maintain it.

**Comment by vedantmgoyal2009** [comment]
That's fine. If there would be any issues, I or moderators would fix it.

**Comment by vedantmgoyal2009** [comment]
@royqh1979 That's fine. If there would be any issues, I or the moderators would fix them.

**Comment by SpecterShell** [comment]
It doesn't recompile the software. Instead it only downloads the installer from GitHub releases.

**Comment by vedantmgoyal2009** [comment]
Do you mean it doesn't install the software?

**Comment by SpecterShell** [comment]
> @SpecterShell Do you mean it doesn't install the software?

Some package managers, for example emerge on gentoo and Homebrew on macOS, do/can download and compile source code to install.

**Comment by vedantmgoyal2009** [comment]
@SpecterShell the action only selects the installer URLs based on the regex and publishes it to WinGet and it would select the same installer URLs which you have added in https://github.com/microsoft/winget-pkgs/pull/70323/files.

**Comment by vedantmgoyal2009** [comment]
@royqh1979 can you please complete the steps mentioned earlier and merge the pull request?

**Comment by vedantmgoyal2009** [comment]
@royqh1979 can you please complete the steps mentioned earlier and merge the pull request?

**Pull request merged**
